services:
  postgres14:
    container_name: postgresql14
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DATABASE: airline
      POSTGRES_USER: airline
      POSTGRES_PASSWORD: airline
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  adminer:
    image: adminer
    ports:
      - "8900:8787"
    restart: always
    networks:
      - spring

  api:
    build: .
    container_name: airline-api
    ports:
      - "8085:8085"
    depends_on:
      - postgres14
    restart: always
    networks:
      - spring

volumes:
  data-postgres:


networks:
  spring:
    name: spring
