server:
  port: 8085

spring:
  application:
    name: "ms-BTG-Pactual"

  data:
    mongodb:
      uri: "mongodb://btg:btg@mongo:27017/btg?authSource=admin"
      database: "btg"

logging:
  level:
    root: INFO